### ISSUE TITLE
Still using Scalaz in the examples?

### ISSUE THREAD

**Issue by asarkar** [underscoreio/advanced-scala-code#2]
The book switched to Cats but the examples still seem to be using Scalaz. A branch, may be?
On a side note, I'd buy the book because I like solving practical exercises, but it's priced too high for me, considering the Kindle version from Odersky himself sells for less than half.

**Comment by noelwelsh** [comment]
We're shifting the case study code over to Cats. The smaller examples are redundant now that we use tut to compile all the code in the book. We'll delete those eventually.

Thanks for the feedback!
